<a href="https://colab.research.google.com/github/lakavathsneha/ML_LAB_2026-27/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [45]:
import numpy as np
list1=[1,2,3,4,5]
array1 = np.array(list1)
print(array1)


[1 2 3 4 5]


In [46]:
import numpy as np
from statistics import mean, median, mode
array1 = np.array([1,2,3,4,5])
print(array1)


[1 2 3 4 5]


In [47]:
# Central Tendency Measures
print("Mean:", mean(array1))         # Mean
print("Median:", median(array1))     # Median
print("Mode:", mode(array1))         # Mode

# Measures of Dispersion
print("Variance:", np.var(array1))            # Variance (Population)
print("Standard Deviation:", np.std(array1))

Mean: 3
Median: 3
Mode: 1
Variance: 2.0
Standard Deviation: 1.4142135623730951


create a 2d array with 2 rows and column


In [48]:
import numpy as np
array1 = np.array([[1,2,3,4,],
                  [5,6,7,8]])
print(array1)


[[1 2 3 4]
 [5 6 7 8]]


In [49]:
# Central Tendency Measures
print("Mean:", mean(list1))         # Mean
print("Median:", median(list1))     # Median
print("Mode:", mode(list1))         # Mode

# Measures of Dispersion
print("Variance:", np.var(array1))            # Variance (Population)
print("Standard Deviation:", np.std(array1))

Mean: 3
Median: 3
Mode: 1
Variance: 5.25
Standard Deviation: 2.29128784747792


create a 3d numpy array


In [50]:
array1 = np.array([[[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]],

                [[13, 14, 15, 16],
                 [17, 18, 19, 20],
                 [21, 22, 23, 24]]])

print(array1)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [51]:
# Central Tendency Measures
print("Mean:", mean(list1))         # Mean
print("Median:", median(list1))     # Median
print("Mode:", mode(list1))         # Mode

# Measures of Dispersion
print("Variance:", np.var(array1))            # Variance (Population)
print("Standard Deviation:", np.std(array1))

Mean: 3
Median: 3
Mode: 1
Variance: 47.916666666666664
Standard Deviation: 6.922186552431729


In [52]:
array1 = np.array([10,20,30,40])
print(array1.dtype)


int64


In [53]:
print(array1.size)

4


In [54]:
print(array1.ndim)

1
